fix: use computed prop so we can mutate it w/o dom reload side effects
radiorabe/klangbecken-ui pull request #118
Opened 2020-09-11 12:25 UTC by hairmare

This is part of preparing for eslint v7 and it's the "standard" fix for simple getting rid of the following linter error:

```
error: Unexpected mutation of "show" prop (vue/no-mutating-props) at src/components/Login.vue:4:16
```

Instead of merging this we might also consider a more aggressive refactoring on the login component, but then again what we already have is working fine and the user base isn't large enough to warrant making the login experience nicer (ie. by supporting sso through keycloak).

2020-09-11 15:04 UTC, smlz requested changes
I just checked, how it is done with in the other dialogs. I think `:value="show"` is the way to go. See here for example: https://github.com/radiorabe/klangbecken-ui/blob/master/src/components/Edit.vue#L4

BTW: How do I run eslint to get the above error message?

This is what I tried:
```sh
[marco@vern klangbecken-ui]$ ./node_modules/.bin/eslint --version
v7.8.1
[marco@vern klangbecken-ui]$ npm run lint

> klangbecken-ui@0.1.0 lint /home/marco/code/klangbecken-ui
> vue-cli-service lint

 DONE  No lint errors found!
```

2020-09-11 15:04 UTC, smlz commented on src/components/Login.vue
> +      v-model="showForm"
Can you check whether `v-bind:value="show"` here would actually be enough? Then we would not need to add a computed value...

2020-09-17 10:57 UTC, hairmare commented on src/components/Login.vue
> +      v-model="showForm"
I'll check this, I'm pretty sure it's the nicer solution and how it should be.

2020-09-17 10:59 UTC, hairmare commented
> BTW: How do I run eslint to get the above error message?

I was using eslint-plugin-vue:v7.0.0-beta.3 to get in some early testing before it is released.

2020-09-25 07:15 UTC, smlz commented on src/components/Login.vue
> +      v-model="showForm"
Using `v-model` here is clearly wrong. I prefere the `:value="show"` solution, as it is simpler, but if we change this, we should change it everywhere to be consistent:
- https://github.com/radiorabe/klangbecken-ui/blob/1b89023f2fc4abff239c432f33bbaaf051e6aec4/src/components/Edit.vue#L4
- https://github.com/radiorabe/klangbecken-ui/blob/4eac3362192ad676b1da10b8d5fb800044b75fd0/src/components/RemoveConfirmation.vue#L4

2020-09-26 13:09 UTC, hairmare commented on src/components/Login.vue
> +      v-model="showForm"
I got around to checking if the simpler `:value="show"` works and updated this.

2020-09-26 13:10 UTC, merged